name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
  
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  build:
    runs-on: ubuntu-latest
    name: 'Build'
    needs: [validate]
    defaults:
      run:
        working-directory: terraform

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -lock=false

  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy'
    needs: [build]
    defaults:
      run:
        working-directory: terraform
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -lock=false
