name: 'Destroy'

on:
  workflow_dispatch:

jobs:
  validate:
    name: 'Destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
  
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -lock=false
