name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  BUCKET:  "bucket-atlas-violencia-devops"

jobs:
  terraform:
    name: 'Validate'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  build:
    runs-on: ubuntu-latest
    name: 'Build'
    needs: [terraform]
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="bucket=$BUCKET"

    - name: Terraform Plan
      run: terraform plan -input=false

  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy'
    needs: [build]
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="bucket=$BUCKET"

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
